version: '3.2'

services:

  alpine-spa-sample:
    build: .
    image: alpine-spa-sample:v1.1
    ports:
      - 3001:80
    volumes:
      # Mount source-code for development
      - ./public:/usr/share/nginx/html


