version: '3.1'

services:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3000:80
    environment:
      - PMA_HOST=192.168.2.64
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=300M
      - MEMORY_LIMIT=2048M
      - MAX_EXECUTION_TIME=3600
